# GitHub Repository Settings
# This file can be used with the GitHub Settings App (https://github.com/apps/settings)
# to manage repository settings as code.

repository:
  # Repository information
  name: terraform-provider-popsink
  description: Terraform Provider for Popsink - Manage your Popsink data pipelines as Infrastructure as Code
  homepage: https://registry.terraform.io/providers/popsink/popsink/latest/docs
  topics:
    - terraform
    - terraform-provider
    - popsink
    - infrastructure-as-code
    - golang
    - data-pipelines
    - iac

  # Repository features
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  has_discussions: true

  # Default branch
  default_branch: main

  # Allow merge strategies
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true

  # Automatically delete head branches after pull requests are merged
  allow_update_branch: true

  # Suggested merge commit message
  squash_merge_commit_title: PR_TITLE
  squash_merge_commit_message: PR_BODY
  merge_commit_title: PR_TITLE
  merge_commit_message: PR_BODY

# Branch protection rules
branches:
  - name: main
    protection:
      # Require pull request reviews before merging
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions:
          users: []
          teams: []

      # Require status checks to pass before merging
      required_status_checks:
        strict: true
        contexts:
          - "test / Format Check"
          - "test / Lint"
          - "test / Go Mod Tidy"
          - "test / Unit Tests (ubuntu-latest, 1.23)"
          - "test / Build"
          - "security / Dependency Vulnerability Scan"

      # Enforce restrictions on who can push to the branch
      enforce_admins: false

      # Require linear history
      required_linear_history: false

      # Allow force pushes
      allow_force_pushes: false

      # Allow deletions
      allow_deletions: false

      # Require conversation resolution before merging
      required_conversation_resolution: true

      # Restrictions on who can push to this branch
      restrictions:
        users: []
        teams: []
        apps: []

# Collaborators and teams configuration
# Uncomment and customize as needed
# teams:
#   - name: maintainers
#     permission: admin
#   - name: contributors
#     permission: write
#   - name: community
#     permission: read

# collaborators:
#   - username: octocat
#     permission: push

# Issue and PR labels
# These should match the labels defined in .github/labels.yml
# Labels are managed by the labeler action and labels.yml file

# Milestones
# milestones:
#   - title: v1.0.0
#     description: First stable release
#     state: open
#   - title: v1.1.0
#     description: Minor improvements and new features
#     state: open

# Security settings
# Note: Some security settings can only be configured through the GitHub UI
# - Security advisories
# - Dependabot alerts
# - Dependabot security updates
# - Code scanning
# - Secret scanning
