name: Bug Report
description: Report a bug or unexpected behavior in the Terraform Provider for Popsink
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug you encountered
    validations:
      required: true

  - type: textarea
    id: terraform-config
    attributes:
      label: Terraform Configuration
      description: Please provide the relevant Terraform configuration that triggers the bug.
      placeholder: |
        terraform {
          required_providers {
            popsink = {
              source = "popsink/popsink"
            }
          }
        }

        resource "popsink_example" "test" {
          # your configuration here
        }
      render: hcl
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run 'terraform init'
        2. Run 'terraform apply'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output / Logs
      description: Please paste any relevant error messages or logs. This will be automatically formatted as code.
      placeholder: Paste error messages or logs here
      render: shell

  - type: input
    id: terraform-version
    attributes:
      label: Terraform Version
      description: Run `terraform version` to find this
      placeholder: "e.g., 1.6.0"
    validations:
      required: true

  - type: input
    id: provider-version
    attributes:
      label: Provider Version
      description: Which version of the Popsink provider are you using?
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "e.g., Ubuntu 22.04, macOS 14.0, Windows 11"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as workarounds you've tried or related issues.
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/popsink/terraform-provider-popsink/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
